[package]
name = "terminal"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3.6.1"
chrono = "0.4.42"
crossterm = "0.27"
dirs = "6.0.0"
eframe = "0.33.2"
egui_extras = { version = "0.33.2", features = ["all_loaders"] }
image = "0.25.9"
ratatui = "0.29.0"
reqwest = { version = "0.12.25", features = ["blocking"] }
rfd = "0.16.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
whoami = "1.6.1"
winreg = "0.55.0"


[build-dependencies]
winres = "0.1"
